# Generated by Django 6.0.6 on 2026-06-18 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_pedido', models.CharField(max_length=50, unique=True)),
                ('cliente_nombre', models.CharField(max_length=255)),
                ('cliente_email', models.EmailField(max_length=254)),
                ('cliente_telefono', models.CharField(max_length=50)),
                ('cliente_direccion', models.CharField(blank=True, max_length=255)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('titular_pago', models.CharField(max_length=255)),
                ('operacion_pago', models.CharField(max_length=100)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de verificación'), ('pagado', 'Pagado / Verificado'), ('enviado', 'Enviado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camiseta_nombre', models.CharField(max_length=255)),
                ('talla', models.CharField(max_length=10)),
                ('version', models.CharField(max_length=50)),
                ('nombre_personalizado', models.CharField(blank=True, default='', max_length=100)),
                ('numero_personalizado', models.CharField(blank=True, default='', max_length=10)),
                ('con_short', models.BooleanField(default=False)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('camiseta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.camiseta')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='tienda.pedido')),
            ],
        ),
    ]
