# Generated by Django 6.0.6 on 2026-06-25 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('calificacion', models.PositiveIntegerField(default=5)),
                ('comentario', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('camiseta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='productos.camiseta')),
            ],
        ),
    ]
